name: Rebuild website on Cloudflare Pages

on:
   schedule:
      - cron: '0 */6 * * *'
   workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Rebuild website
           run: curl -X POST -d {} ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
